[package]
name = "dns-rs"
version = "0.1.0"
authors = ["D. Ryan Hild <d.ryan.hild@gmail.com>"]
repository = "https://github.com/dhild/dns-rs.git"
homepage = "https://github.com/dhild/dns-rs.git"
license = "MIT"
readme = "README.md"
documentation = "http://dhild.github.io/dns-rs/"
description = "DNS library for dealing with resource records."

[dependencies]
clippy = {version = "*", optional = true}

[features]
default = []
dev = ["clippy"]
